@echo off
echo Starting Customer Complaint Resolver Agent...
echo Ensuring dependencies are installed...
pip install -r requirements.txt
echo.
echo Running Verification Demo (Unbuffered)...
python -u main.py
pause
